### ISSUE TITLE
[ENH] Paper Implementation using Tensorflow/Keras

### ISSUE THREAD

**Issue by EverLookNeverSee** [rixez/Brats21_KAIST_MRI_Lab#1]
Hi @rixez 

I would like to implement this paper using tensorflow and keras library.
I have a problem with **axial attention** section and i can not understand it in details. Could you please give me some hints and/or resources to find out how to implement the axial attention?

Regards

**Comment by rixez** [comment]
Hi @EverLookNeverSee,
Thank you for your interest in this repo!
The axial attention in this package was adopted from [Axial Attention](https://github.com/lucidrains/axial-attention). For the reference paper, you can check out [the paper](https://arxiv.org/abs/2003.07853).
The implementation of axial attention in this repo can be found here:
https://github.com/rixez/Brats21_KAIST_MRI_Lab/blob/d05fba87d392f4ab9cc6c64c1658688f7d27a3d0/nnunet/network_architecture/generic_UNet.py#L377
And the trainer for the axial attention model can be found here:
https://github.com/rixez/Brats21_KAIST_MRI_Lab/blob/d05fba87d392f4ab9cc6c64c1658688f7d27a3d0/nnunet/training/network_training/competitions_with_custom_Trainers/BraTS2020/nnUNetTrainerV2BraTSRegions_moreDA.py#L363
To train the model, you can replace the trainer in the readme with the appropriate trainer like this:
```nnUNet_train 3d_fullres nnUNetTrainerV2BraTSRegions_DA4_BN_BD_axialattention_unet <TASK_ID> <FOLD> --npz ```

I think the syntax would be similar in tensorflow. But note that we did not use the axial attention model in the final ensemble for the competition.
Thank you and let me know if you have any more questions!

**Comment by miladsade96** [comment]
@rixez 
Thanks for the explanation.
If i have a question, i will ask you.
