### ISSUE TITLE
Stop training to test

### ISSUE THREAD

**Issue by wxr521314** [rixez/Brats21_KAIST_MRI_Lab#10]
hi
    When I was training, I found that after 300 epoch, my dice was basically unchanged, and loss also converged. I wanted to stop training for testing, how should I modify it? Except for setting the training epoch to 300.Is there another way? For example, can I use the results in the middle of training to predict? How do I change the code?

**Comment by rixez** [comment]
Hi,
I believe you can just do Ctrl+c to stop the training. The model with the best validation score is saved as `model_best.model` in the saved folder so you can just pass that to the argument `-chk` for the `nnUNet_predict` command like this:
```
nnUNet_predict -i <input_folder> -o <output_folder1> -t <TASK_ID> -m 3d_fullres -tr nnUNetTrainerV2BraTSRegions_DA4_BN_BD --save_npz -chk model_best
```

I hope this works for you!
