### ISSUE TITLE
About  dataset_conversion

### ISSUE THREAD

**Issue by Zhuofei-Wang** [rixez/Brats21_KAIST_MRI_Lab#12]
When I run the task500_brats_2021.py file, I get an error at line 799：”TypeError: my_evaluate_folder() missing 1 required positional argument: 'gt_folder'” 
What parameters should be written here?

**Comment by rixez** [comment]
Hi @l0enkidu0l,
You should put the folder containing the ground truth segmentation label for the `gt_folder` argument.
If you use nnUNet's preprocessing pipeline with the BraTS dataset, this folder should be `nnUNet_preprocessed/Task500_BraTS2021/gt_segmentations`.
