### ISSUE TITLE
How to calculate a single sample segmentation metrics?

### ISSUE THREAD

**Issue by panovr** [rixez/Brats21_KAIST_MRI_Lab#13]
Hi,
  I can use your docker image to generate the segmentation result for a single sample. May I ask that how can I calculate the segmentation metrics like Dice score and HD95 score of ET, TC and WT regions for this sample suppose the ground-truth segmentation mask exist?
  Thanks!

**Comment by rixez** [comment]
Hi @panovr,

To calculate the segmentation metrics, you can use this function:

https://github.com/rixez/Brats21_KAIST_MRI_Lab/blob/6dfd1a4cb66be5ec94b9b7c102b0e5e89d8ec657/nnunet/dataset_conversion/Task500_BraTS_2021.py#L664

Thanks!

**Comment by panovr** [comment]
May I ask that how the metrics of sample BraTS2021_00174 and BraTS2021_01784 in your paper were calculated? Because these two samples are in the Validation dataset, so I think there were no corresponding ground-truth segmentations supplied for them.
Thanks!

**Comment by rixez** [comment]
You are right. There were no ground-truth segmentations for the validation dataset. The metrics for the two validation samples were calculated and provided by the organizers during the challenge. You can check this [link](https://www.synapse.org/#!Synapse:syn27046444/wiki/616991) for the continuous evaluation of  the BraTS challenge.
