### ISSUE TITLE
How to train the model with docker image?

### ISSUE THREAD

**Issue by panovr** [rixez/Brats21_KAIST_MRI_Lab#15]
Hi,
  is it possible train the model with docker image?
  Thanks!

**Comment by rixez** [comment]
Hi @panovr,

Yes, it is possible to train the model with docker image. I haven't tried this though so I'm not sure about the training speed or accuracy.

You can do this by making a script that calls the training command, similar to the inference_v2.py file and build a docker image with that.

I hope this helps.
