### ISSUE TITLE
abou  AxialAttention

### ISSUE THREAD

**Issue by zgyReign** [rixez/Brats21_KAIST_MRI_Lab#17]
Hello, author. I want to ask you, did you invoke the AxiaUet class defined in generic_Unet later? I searched for a long time and didn’t find any traces of invocation.thanks very much

**Comment by rixez** [comment]
Hello @zgyReign,

The AxialUnet class was the initial prototype for the axial attention Unet. The class was then merged into the GenericUnet class. You can just use the GenericUnet class.
