### ISSUE TITLE
about nnUNetTrainerV2BraTSRegions_moreDA.py

### ISSUE THREAD

**Issue by zhao9chen99999** [rixez/Brats21_KAIST_MRI_Lab#18]
your work is so great!!
i am try to deal with my own dataset,and, i wrote these:
<img width="302" alt="image" src="https://user-images.githubusercontent.com/57703720/228712064-e1f9b0e9-649f-4f58-9427-5b8e6b12eedc.png">
but as soon as i run these,the error came as :
<img width="641" alt="image" src="https://user-images.githubusercontent.com/57703720/228712584-a77a945a-fc0f-4958-8b51-180beb1085a2.png">
so i m wondering where do i need to edit to let nnunet recongnize my nnUNetTrainerV2XXXXRegions_moreDA.py

**Comment by zhao9chen99999** [comment]
i also tried to add this in nnUNetTrainerV2BraTSRegions_moreDA.py:
<img width="1006" alt="image" src="https://user-images.githubusercontent.com/57703720/228716541-19a0af9b-f625-4069-bcd5-d483b769bfcb.png">
but still:
<img width="631" alt="image" src="https://user-images.githubusercontent.com/57703720/228716650-f40d39d0-7a24-4704-a177-15a79d48c430.png">
just dont know how to make the changes recongnized by nnunet

**Comment by rixez** [comment]
Hi @zhao9chen99999, what is the command that you used for training?

**Comment by zhao9chen99999** [comment]
> Hi @zhao9chen99999, what is the command that you used for training?

nnUNet_train 3d_fullres nnUNetTrainerV2BraTSRegions_DA4_BN_BD_lymphomaUnet 567 0 --npz # BL +lymphomaunet config

**Comment by rixez** [comment]
Have you tried the other trainer classes in the file?
If other trainer classes cannot be found as well, you might want to check this function, which looks for the trainer class:
https://github.com/rixez/Brats21_KAIST_MRI_Lab/blob/65284cc87718c0e64e3271d0ff43b945174de41c/nnunet/training/model_restore.py#L23

**Comment by zhao9chen99999** [comment]
> recursive

this one can work fine:
<img width="1024" alt="image" src="https://user-images.githubusercontent.com/57703720/228870680-605fa20b-4f6d-4026-8515-01cc77f740d9.png">
but this one can't:
<img width="1053" alt="image" src="https://user-images.githubusercontent.com/57703720/228870980-1b3b05ba-f3fd-4ee6-b48a-0b0b4a802047.png">
next i changed nnUNetTrainerV2BraTSRegions_moreDA.py -nnUNetTrainerV2BraTSRegions_DA4_BN_BD from512 to 1024：
<img width="975" alt="image" src="https://user-images.githubusercontent.com/57703720/228871374-e9d58f89-2dd7-4e48-b700-313bc9bac45b.png">
but the output net architect results is still 512，not 1024，so i wonder maybe， the edition on nnUNetTrainerV2BraTSRegions_moreDA.py doesn't work？if that’ s true，which file do i need to edit ？thx！！！

**Comment by zhao9chen99999** [comment]
i common out the nnUNetTrainerV2BraTSRegions_DA4_BN_BD in nnUNetTrainerV2BraTSRegions_moreDA.py :
<img width="771" alt="image" src="https://user-images.githubusercontent.com/57703720/228996195-0905fd27-1632-48a6-9b75-f0df12210630.png">
i found the nnunet still could work with the nnUNetTrainerV2BraTSRegions_DA4_BN_BD in nnUNetTrainerV2BraTSRegions_moreDA.py :
<img width="612" alt="image" src="https://user-images.githubusercontent.com/57703720/228996572-6ee83fb8-dab3-4df6-9035-a1927d85580b.png">

**Comment by zhao9chen99999** [comment]
in fact, i tried delete the nnUNetTrainerV2BraTSRegions_moreDA.py and the nnunet can still run:
<img width="625" alt="image" src="https://user-images.githubusercontent.com/57703720/229004218-4cb392c1-82b6-4344-86cc-6c797ca112c3.png">
that confuse me,i dont know what to do next

**Comment by rixez** [comment]
One possible reason is that you are running the training command with a different copy of the nnUNet library. Please check which file the nnUNet_train command runs from.

**Comment by zhao9chen99999** [comment]
> One possible reason is that you are running the training command with a different copy of the nnUNet library. Please check which file the nnUNet_train command runs from.

thx for your anwser,it really helps a lot!
