### ISSUE TITLE
output channel

### ISSUE THREAD

**Issue by wxr521314** [rixez/Brats21_KAIST_MRI_Lab#5]
hi ，
Why is the output of a network two-channel? What do two channels represent? Is the first channel the background and the second channel the foreground
![383ab94c-f588-48a7-959e-8d759a4ed334](https://user-images.githubusercontent.com/53425125/154430259-d1209669-b79d-40a5-ba98-ccf1cf20bc80.png)
?

**Comment by rixez** [comment]
That's correct. The two channels represent background and foreground.
