### ISSUE TITLE
Batch_size in the modification of inference by Ruhe

### ISSUE THREAD

**Issue by wxr521314** [rixez/Brats21_KAIST_MRI_Lab#6]
Hi, I would like to ask whether batch_size is 1 in the inference time. If I want to run batch_size=2, how do I change it?

**Comment by rixez** [comment]
During inference, the volume is processed one by one. Depending on the configuration setup by nnUnet, it will divide the volume into multiple sub-volumes, predict the segmentation for each of them, and aggregate the results. So the batch size for each volume is the number of sub-volumes. By default, the inference codes also perform test-time augmentation (TTA) by flipping each subvolume along each axis and averaging the prediction results (8 predictions). If you want faster inference at the cost of slightly lower segmentation quality, you can try disabling TTA when running `nnUNet_predict`.
