### ISSUE TITLE
Providing Dockerfile

### ISSUE THREAD

**Issue by blakedewey** [rixez/Brats21_KAIST_MRI_Lab#7]
@rixez Do you have the Dockerfile that you used to create the container on Dockerhub? I would like to recreate it to use a different CUDA version to work on some of our older cards.

**Comment by rixez** [comment]
Hi @blakedewey,
I just uploaded the dockerfile and other scripts required to make the docker container. Please check it out!
https://github.com/rixez/Brats21_KAIST_MRI_Lab/blob/6dfd1a4cb66be5ec94b9b7c102b0e5e89d8ec657/Dockerfile#L1

**Comment by blakedewey** [comment]
Amazing! Thanks!
